/*
 * This source file was generated by the Gradle 'init' task
 */
package sing.cli

class App {
    String getGreeting() {
        return 'Hello Groovy (and Sonar??)!!!'
    }

    static void main(String[] args) {
        println new App().greeting
    }
}
