name: Gradle Build

on: workflow_call

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: distributionsZip
          path: |
            ./hello-groovy/build/distributions/hello-groovy-*.zip
      - uses: actions/upload-artifact@v4
        with:
          name: fatJar
          path: |
            ./hello-groovy/build/libs/hello-groovy-*-all.jar
      - run: ./gradlew buildAppDeb
      - uses: actions/upload-artifact@v4
        with:
          name: deb-deliverables
          path: |
            ./hello-groovy/build/distributions/hello-groovy_*_amd64.deb
