name: Gradle Build

on: workflow_call

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: distributionsZip
          path: |
            ./app/build/distributions/app.zip
      - uses: actions/upload-artifact@v4
        with:
          name: fatJar
          path: |
            ./app/build/libs/app-all.jar
