name: Build and Test on Push
on:
  push:
    branches:
      - "*"

jobs:
  gradle-build:
    uses: ./.github/workflows/gradle-build.yml
  sonarcloud:
    needs: gradle-build
    uses: ./.github/workflows/quality-sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
